16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.address`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.address` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.automotive`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.automotive` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.bank`. (factory.py:76)
16:08:18 [DEBUG] Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider. (factory.py:86)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.barcode`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.barcode` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.color`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.color` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.company`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.company` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.credit_card`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.credit_card` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.currency`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.currency` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.date_time`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.date_time` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:106)
16:08:18 [DEBUG] Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:106)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.geo`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.geo` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.internet`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.internet` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:106)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.job`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.job` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.lorem`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.lorem` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.misc`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.misc` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.person`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.person` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.phone_number`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.phone_number` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:106)
16:08:18 [DEBUG] Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:106)
16:08:18 [DEBUG] Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:106)
16:08:18 [DEBUG] Looking for locale `en_US` in provider `faker.providers.ssn`. (factory.py:76)
16:08:18 [DEBUG] Provider `faker.providers.ssn` has been localized to `en_US`. (factory.py:95)
16:08:18 [DEBUG] Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:106)
16:08:18 [DEBUG] Starting new HTTPS connection (1): www.dnd5eapi.co:443 (connectionpool.py:1003)
16:08:19 [DEBUG] https://www.dnd5eapi.co:443 "GET /api/ HTTP/1.1" 200 737 (connectionpool.py:456)
